Task suspend/resume/abortdelay
RT-Thread-packages/FreeRTOS-Wrapper pull request #15
Opened 2022-06-29 08:22 UTC by tangzz98

Simple task utility functions

2022-06-29 21:13 UTC, mysterywolf requested changes

2022-06-29 21:13 UTC, mysterywolf commented on FreeRTOS/task.c
> +        thread->user_data = ( rt_ubase_t ) pxHookFunction;
这个地方有问题 user_data不能被占用 在TaskHandle_t里增加一个成员变量，来处理此事。 
RT-Thread的结构体的成员变量，读取没有问题，如果要是写，一定要在pr里和我说一下，这种写rtt内部成员变量的行为的很容易会带来意想不到的风险。

2022-06-30 08:09 UTC, tangzz98 commented on FreeRTOS/task.c
> +        thread->user_data = ( rt_ubase_t ) pxHookFunction;
加了成员变量以后线程动态创建用RT_KERNEL_MALLOC和rt_thread_init，删除时动静态都用rt_thread_detach。动态创建的线程给rt_thread_t->cleanup赋值，空闲线程调用cleanup释放内存。rt_thread_t->cleanup应该只有pthread和lwp用到。

2022-07-02 01:59 UTC, mysterywolf requested changes

2022-07-02 01:59 UTC, mysterywolf commented on FreeRTOS/task.c
> +        void * stack_start;
```suggestion
        void * stack_start = RT_NULL;
```

2022-07-02 18:41 UTC, merged